spring.application.name=cordillera-kpi-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/cordillera_kpi_db
spring.datasource.username=postgres
spring.datasource.password=tu_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always